### ISSUE TITLE
Windows Linking does not work

### ISSUE THREAD

**Issue by sofiha-sven** [ikalogic/sp209api-test-minimal#1]
When trying to build the Project (Windows Qt 5.12. VS2019, just for reference, should not matter in this case), it fails to link, because the .lib files for DLLs are missing.

I was able to generate them using this instruction: https://github.com/Neargye/hello_tf_c_api/blob/master/doc/create_lib_file_from_dll_for_windows.md

Would be nice, to have them in this project right away

**Comment by ikalogic** [comment]
Thank you @sofiha-sven i have just added the *.lib.

I also did a major update to the API, documentation underway..

**Comment by sofiha-sven** [comment]
thank you, i will test this asap
