### ISSUE TITLE
number of captured samples with ext_clk is not correct ?

### ISSUE THREAD

**Issue by metebalci** [ikalogic/sp209api-test-minimal#4]
I have a simple code, very similar to the one on the website with `trig.type = SP209API_TRG_NOTRIG` but also with `ext_clk = true` and `ext_clk_pol = CLK_POL_DUAL`.

I set sampling_depth to 1M.

- if I set post_trig_samples to 0.5M, after the capture, I expect to get (from sp209api_get_available_samples) total_available_samples=1M and post_trig_samples=0.5M. However, I receive different numbers, mostly around 333333 but sometimes different, but the same number for both.
 
- if I set post_trig_samples to 1M (same as sampling_depth), after the capture, again I receive something mostly around 666666 for both (but sometimes a different number).

So it looks like the actual number of samples captured is ~66% of what is set to post_trig_samples.

I checked the same code with `ext_clk = false` and then it captures correct number of samples but again this is equal to post_trig_samples and not to total_available_samples, and these two are same (or very similar).

Am I missing something ?

(Edit: This is on Linux, using the libraries in this repository)

**Comment by ikalogic** [comment]
@metebalci

We fixed the problem, the fix will be pushed in the next few hours.

Thank you very much,

**Comment by ikalogic** [comment]
@metebalci it should be fixed now. I'll close the issue, please don't hesitate to re-open if needed.
